#!/bin/sh

# The GPLv2 License
#
#   Copyright (C) 2025 pyamsoft
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License along
#   with this program; if not, write to the Free Software Foundation, Inc.,
#   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# adjust-pci-latency
# by: pyamsoft <developer(dot)pyamsoft(at)gmail(dot)com>

NAME="$(basename "$0")"
readonly VERSION="0.0.3"
readonly NAME

# Taken from, with modification
# https://github.com/CachyOS/CachyOS-Settings/blob/master/usr/bin/pci-latency
#
# Also see here
# https://wiki.archlinux.org/title/Gaming#Improve_PCI_Express_Latencies
# https://wiki.archlinux.org/title/Professional_audio#System_configuration

# This script is designed to improve the performance and reduce audio latency
# for sound cards by setting the PCI latency timer to an optimal value of 80
# cycles. It also resets the default value of the latency timer for other PCI
# devices, which can help prevent devices with high default latency timers from
# causing gaps in sound.

readonly KERNEL_LOCKDOWN_FILE="/sys/kernel/security/lockdown"
readonly KERNEL_LOCKDOWN_MODE_NONE="none"

readonly ERR_NO_ROOT=1
readonly ERR_NO_SETPCI=2
readonly ERR_BAD_ARG=3
readonly ERR_FAIL_SETPCI=4
readonly ERR_KERNEL_LOCKDOWN=5

##
# Log
#
# Accepts arguments in the same format as printf
# $1 message
# $@ arguments
##
_log() {
  _msg="$1"
  shift

  printf -- "[%s]: ${_msg}\n" "${NAME}" "$@"

  unset _msg

  return 0
}

##
# Error Log
#
# Accepts arguments in the same format as printf
# $1 message
# $@ arguments
##
_elog() {
  _log "$@" 1>&2 || return 1
  return 0
}

_check_kernel_lockdown() {
  _check_kernel_lockdown__yolo="$1"

  _kernel_lockdown_mode=""
  if [ -r "${KERNEL_LOCKDOWN_FILE}" ]; then
    # Grab the [current-mode] and remove the [ ]
    _kernel_lockdown_mode="$(grep -o '\[.*\]' "${KERNEL_LOCKDOWN_FILE}" | tr '[' ' ' | tr ']' ' ' | awk '{ print $1 }')"
  fi

  if [ -n "${_kernel_lockdown_mode}" ]; then
    if [ "${_kernel_lockdown_mode}" = "${KERNEL_LOCKDOWN_MODE_NONE}" ]; then
      # Lockdown mode is NONE, approved
      unset _kernel_lockdown_mode
      unset _check_kernel_lockdown__yolo
      return 0
    fi

    if [ -n "${_check_kernel_lockdown__yolo}" ] && [ "${_check_kernel_lockdown__yolo}" -ne 0 ]; then
      _log 'Ignoring lockdown mode, attempting setpci calls anyway'
      unset _kernel_lockdown_mode
      unset _check_kernel_lockdown__yolo
      return 0
    else
      _log 'Kernel lockdown mode prevents setpci calls. Current mode: "%s"' "${_kernel_lockdown_mode}"
      unset _kernel_lockdown_mode
      unset _check_kernel_lockdown__yolo
      return 1
    fi
  else
    _log 'Unable to determine current kernel lockdown mode'
    if [ -n "${_check_kernel_lockdown__yolo}" ] && [ "${_check_kernel_lockdown__yolo}" -ne 0 ]; then
      _log 'Ignoring lockdown mode, attempting setpci calls anyway'
      unset _kernel_lockdown_mode
      unset _check_kernel_lockdown__yolo
      return 0
    else
      _log 'Kernel lockdown mode is unknown. Prevent setpci calls just to be sane.'
      unset _kernel_lockdown_mode
      unset _check_kernel_lockdown__yolo
      return 1
    fi
  fi
}

_tweak_pci_gaming() {
  _log 'Gaming: Tweaking system PCI latency...'

  # Reset the latency timer for all PCI devices
  _log '[Baseline]: Adjust all PCI latency to 20.'
  setpci -v -s '*:*' latency_timer=20 || {
    _elog 'Failed resetting latency timer to 20 for all PCI'
    return 1
  }

  _log '[Bus]: Adjust all bus 0 device PCI latency to 0.'
  setpci -v -s '0:0' latency_timer=0 || {
    _elog 'Failed resetting latency timer to 0 for all bus 0 devices'
    return 1
  }

  # Set latency timer for all sound cards
  _log '[Audio]: Adjust all sound device PCI latency to 80'
  setpci -v -d "*:*:04xx" latency_timer=80 || {
    _elog 'Failed adjusting latency timer to 80 for all sound devices'
    return 1
  }

  _log 'Gaming: PCI latency times adjusted!'
  return 0
}

_tweak_pci_audio() {
  _log 'Pro-Audio: Tweaking system PCI latency...'

  # Reset the latency timer for all PCI devices
  _log -- '[Baseline]: Adjust all PCI latency to b0.'
  setpci -v -d '*:*' latency_timer=b0 || {
    _elog -- 'Failed resetting latency timer to b0 for all PCI'
    return 1
  }

  _log '[Audio]: Adjust all sound device PCI latency to ff'
  setpci -v -d "*:*:04xx" latency_timer=ff || {
    _elog 'Failed adjusting latency timer to ff for all sound devices'
    return 1
  }

  _log 'Pro-Audio: PCI latency times adjusted!'

  return 0
}

_usage() {
  printf -- '%s\n' "$(
    cat <<EOF
${NAME} ${VERSION}

usage: ${NAME} [--ignore-kernel-lockdown-mode] <mode>

where <mode> is one of:

game
games
gaming                           Adjust system PCI latency for lower latency at the cost
                                 of system overall throughput.

audio
proaudio
pro-audio                        Adjust system PCI latency to maximize the PCI latency timer
                                 of PCI sound card devices for audio production.

Options:
--ignore-kernel-lockdown-mode    Modern kernels can prevent setpci calls at runtime. If you run a lockdown mode,
                                 this script will NOT WORK. You can "try anyway" by setting this flag.

EOF
  )"
}

##
# Return codes
# 0: success
# 1: root priv needed
# 2: setpci missing
# 3: invalid command
# 4: action failed
main() {
  if ! command -v setpci >/dev/null; then
    _elog 'You must have "setpci"'
    return "${ERR_NO_SETPCI}"
  fi

  action=""
  yolo=0

  while [ -n "$1" ]; do
    case "$1" in
    --ignore-kernel-lockdown-mode)
      yolo=1
      ;;
    game | games | gaming)
      action="game"
      ;;
    audio | proaudio | pro-audio)
      action="audio"
      ;;
    *)
      _usage || return "${ERR_BAD_ARG}"
      return "${ERR_BAD_ARG}"
      ;;
    esac

    shift
  done

  # Check if the script is run with root privileges
  if [ "$(id -u)" -ne 0 ]; then
    _elog 'Error: This script must be run with root privileges.'
    return "${ERR_NO_ROOT}"
  fi

  _check_kernel_lockdown "${yolo}" || return "${ERR_KERNEL_LOCKDOWN}"

  case "${action}" in
  game)
    _tweak_pci_gaming || {
      _elog 'Failed to adjust PCI latency for gaming.'
      return "${ERR_FAIL_SETPCI}"
    }
    ;;
  audio)
    _tweak_pci_audio || {
      _elog 'Failed to adjust PCI latency for pro-audio.'
      return "${ERR_FAIL_SETPCI}"
    }
    ;;
  *)
    _usage || return "${ERR_BAD_ARG}"
    return "${ERR_BAD_ARG}"
    ;;
  esac

  return 0
}

main "$@" || exit "$?"
exit 0
